spring:
  application:
    name: SpringOAuth2Project

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: GOOGLE_CLIENT
            client-secret: GOOGLE_SECRET
            scope:
              - email
              - profile
          github:
            client-id: GITHUB_ID
            client-secret: GITHUB_SECRET
            scope:
              - read:user
              - user:email

        provider:
          google:
            authorization-uri: 
            token-uri: 
            user-info-uri: 
            user-name-attribute: sub

          github:
            authorization-uri: 
            token-uri: 
            user-info-uri: 
            user-name-attribute: id

